# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-22 01:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name_plural': '20.用户表'},
        ),
        migrations.AlterModelOptions(
            name='userauthtoken',
            options={'verbose_name_plural': '21.用户token表'},
        ),
    ]
