# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-23 05:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181122_0932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userauthtoken',
            options={'verbose_name_plural': '21.用户'},
        ),
    ]
